version: '3.4'
services:
  database:
    build: ./database
    volumes:
      - type: bind
        source: ./database
        target: /app
    ports:
      - 4001:4001
      - 4400:4400
      - 4500:4500
      - 4501:4501
      - 8083:8083
      - 9099:9099
      - 9150:9150
      - 9199:9199
      - 9299:9299

  frontend:
    build: ./frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    depends_on:
      - database
    ports:
      - 5173:5173
